<plominodatabase id="iol_sp">
  <design>
    <element id="onFirmaOk" title="onFirmaOk" type="PlominoAgent">
      <id type="Products.Archetypes.Field.StringField">onFirmaOk</id>
      <Content type="Products.Archetypes.Field.TextField"><![CDATA[docId = args[0]
data = args[1]
db=context.getParentDatabase()

try:
    doc = db.getDocument('00001-2019-firmadigitale')
    req = doc.getItem('REQUEST_DATA',[])
    req.append(doc.REQUEST)
    doc.setItem('REQUEST_DATA',req)
    doc.setIte,('LAST_REQUEST',doc.REQUEST)
                
except Exception as err:
    doc = db.getDocument('00001-2019-firmadigitale')
    doc.setItem('ERRORE_GENERICO',1)
    context.getParentDatabase().resources.customscripts.sendMailPlone(doc=doc,azione='pagopa-ko')
    context.plone_utils.addPortalMessage('Errore nel firma digitale %s' %err, 'error')]]></Content>
      <RunAs type="Products.Archetypes.Field.StringField">OWNER</RunAs>
    </element>
  </design>
</plominodatabase>
